[package]
name = "ragit-cli"
version = "0.4.1"
edition = "2024"
license = "MIT"
description = "cli argument parser for ragit"
repository = "https://github.com/baehyunsol/ragit"
documentation = "https://docs.rs/ragit-cli"

[dependencies]
