[package]
name = "ragit-pdl"
version = "0.3.3"
edition = "2021"
license = "MIT"
description = "pdl parser for ragit"

[dependencies]
base64 = "0.22.1"
image = "0.25.5"
lazy_static = "1.5.0"
ragit-fs = { path = "../fs", version = "0.3.3" }
regex = "1.11.1"
serde_json = "1.0.139"
tera = "1.20.0"
